several misc fixes + LREC plot update
swerik-project/scripts pull request #1
Opened 2024-04-16 08:17 UTC by BobBorges

sorry for mixing multiple things here

2024-04-16 08:51 UTC, BobBorges commented
merge PRs and new release of pyriksdagen should fix this.

2024-06-10 09:33 UTC, ninpnin requested changes

2024-06-10 09:33 UTC, ninpnin commented on src/KWIC-iter-search.py
> -    parser.add_argument("-e", "--end", type=int, default=2022, help="End year")
Would this work with start=None and end=None? If yes, we should do that.

2024-06-10 09:33 UTC, ninpnin commented on src/add_modern_pagenumbers.py
> +def pad_nr(protocol):
This is being used in multiple places. Either have it inline, or add to pyriksdagen.

2024-06-10 09:33 UTC, ninpnin commented on src/add_modern_pagenumbers.py
> +def pad_nr(protocol):
@BobBorges @vgkz

2024-06-10 09:33 UTC, ninpnin commented on src/add_modern_pagenumbers.py
> +    xmlpath = f"riksdagen-records/data/{gathering_year}/{pad_nr(protocol_id)}.xml"
Default arg would be better.

2024-06-10 09:33 UTC, ninpnin commented on src/plot/plot-mp-coverage.py
> +    if "N_MP" not in dates.columns:
Replace with a for loop

2024-06-10 09:33 UTC, ninpnin commented on src/plot/plot-mp-coverage.py
> +    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
I would really like to use the ```trainerlog``` module, or other proper logging. That makes it easier to turn these off, only show the important ones and see when they are printed out.

2024-06-19 14:26 UTC, ninpnin requested changes

2024-06-19 14:26 UTC, ninpnin commented on src/ToC/delimit-ToC_2014--.py
>      parser.add_argument("-e", "--end", type=int, default=2022, help="End year")
Remove defaults

2024-06-19 14:26 UTC, ninpnin commented on src/plot/plot-mp-coverage.py
> +ledamot_map = {
This is duplicated, no?

2024-06-19 14:26 UTC, ninpnin commented on src/plot/plot-mp-coverage.py
> +#!/usr/bin/env python3
Description missing

2024-06-19 14:26 UTC, ninpnin commented on src/digorigin.py
> +    parser.add_argument("-s", "--start", type=int, default=1990)
Remove defaults (?)

2024-06-19 14:26 UTC, ninpnin commented on src/cur-prot/add_uuid.py
> +        protocol_id = Path(protocol).stem
Maybe better to get this from the XML TEI element

2024-06-19 14:26 UTC, ninpnin commented on src/KWIC-iter-search.py
> +            raw = rq.readlines()
What is going on here?

2025-01-13 16:15 UTC, ninpnin commented
@BobBorges sounds reasonable, but what's should be do about that?

2025-01-15 10:32 UTC, BobBorges commented
> @BobBorges sounds reasonable, but what's should be do about that?

leave it for now - I'll go through in the next period and check if there's anything we actually want to merge.

2025-01-22 06:53 UTC, BobBorges commented
I'm closing this. Most of the review points are moot as various changes have been or should have been implemented in other ways after this PR was opened. Code for the plots should go in the records repo under `quality` and/or `test/`.

2025-01-22 06:53 UTC, closed without merging